name: Code Linters

on:
  pull_request:
  push:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - uses: pre-commit/actions@v3.0.0
        env:
          SKIP: no-commit-to-branch
